version: "3.9"
services:
  web:
    build: .
    depends_on:
      - "database"
    command: --SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
      - "8443:8443"
  database:
    image: "postgres" # use latest official postgres version
    container_name: "postgres"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "Radhe20$$()" #POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "5432:5432"
